#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION 0x001F00  /* 0.31.0 */
#define CMARK_VERSION_STRING "0.31.0"

#define CMARK_VERSION_MAJOR 0
#define CMARK_VERSION_MINOR 31
#define CMARK_VERSION_PATCH 0

#endif /* CMARK_VERSION_H */
